# -*- coding: utf-8 -*-
"""O altă copie pentru Moscow Housing Prices EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12e1m6x4H3up0EtwkGX6OOVWqQ_soxyTV
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
egorkainov_moscow_housing_price_dataset_path = kagglehub.dataset_download('egorkainov/moscow-housing-price-dataset')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

house_df = pd.read_csv('/kaggle/input/datasets/egorkainov/moscow-housing-price-dataset/data.csv')
print(house_df)

"""**Observation**: 22676 rows, 12 features; good dimensions

# Descriptive Analysis
"""

house_df.info()

"""**Observation**: No null values observed."""

house_df.nunique()

house_df.describe()

"""**Observation**: Possible outliers are in: number of rooms, minutes to metro, area, living area, kitchen area, floor and number of floors

# Finding out the distributions for each quantitative variable
"""

variable_list = ['Price', 'Minutes to metro', 'Number of rooms', 'Area', 'Living area', 'Kitchen area', 'Floor', 'Number of floors']
type(variable_list)

for variable in variable_list:
  plt.hist(house_df[variable], bins = 10)
  plt.title(variable)
  plt.xlabel("Value")
  plt.ylabel("Frequency")
  plt.show()

for variable in variable_list:
  plt.boxplot(x = house_df[variable])
  plt.title('Boxplot for ' + variable)

  plt.show()

"""**Observation**: Dataset is heavily populated with outlier values."""

apartment_type = house_df['Apartment type'].value_counts(normalize=True)
metro_station = house_df['Metro station'].value_counts(normalize=True)
region_location = house_df['Region'].value_counts(normalize=True)
renovation_type = house_df['Renovation'].value_counts(normalize=True)

count_list = [apartment_type, metro_station, region_location, renovation_type]

print(count_list)

"""# Correlation and Feature Importance Analysis"""

import matplotlib.pyplot as plt
import seaborn as sns

#house_copydf = house_copydf.replace({'Yes': 1, 'No': 0, 'yes': 1, 'no': 0})
#house_copydf['furnishingstatus'] = house_copydf['furnishingstatus'].replace({'unfurnished': 0, 'furnished': 1 , 'semi-furnished': 2})

house_copydf = house_df
type(house_copydf)

house_copydf = house_copydf.drop(columns = ["Metro station"])
house_copydf.head()

house_copydf = house_copydf.replace({'Moscow': 1, 'Moscow region': 2})
house_copydf = house_copydf.replace({'New building': 1, 'Secondary': 2})
house_copydf = house_copydf.replace({'Without renovation': 0, 'Cosmetic': 1, 'European-style renovation': 2, 'Designer': 3})

house_copydf.head()

pearson_corr = house_copydf.corr(method='pearson')
print(pearson_corr)

fig, ax = plt.subplots(figsize=(15, 10))
sns.heatmap(pearson_corr, annot=True, cmap='coolwarm')
plt.title("Pearson Correlation Heatmap")
plt.show()

"""many interesting correlations"""

#beginning with the feature analysis

from sklearn.feature_selection import SelectKBest, f_regression

# will pick the price variable as the designated variable for the Univariate Feature Selection Test (ANOVA F-Value)

X = house_copydf.drop("Price", axis=1)
y = house_copydf["Price"]

# Applying SelectKBest with ANOVA F-value
selector = SelectKBest(score_func=f_regression, k='all')
selector.fit(X, y)

# Displaying scores for each feature
feature_scores = pd.DataFrame({'Feature': X.columns, 'Score': selector.scores_})

print(feature_scores.sort_values(by='Score', ascending=False))

# putting it in a barchart

feature_scores = feature_scores.sort_values(by='Score', ascending=True)

plt.barh(feature_scores['Feature'], feature_scores['Score'])

plt.title('Feature Importance Analysis')
plt.xlabel('Score')
plt.ylabel('Variable')
plt.show()

"""3 possible features could be used"""