# -*- coding: utf-8 -*-
"""O altă copie pentru London Housing Prices EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxcGJ3B1Two1PGqVEE7rhmx2w_WtYVPT
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
jakewright_house_price_data_path = kagglehub.dataset_download('jakewright/house-price-data')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

"""# Importing dataset"""

house_prices_df = pd.read_csv("/kaggle/input/datasets/jakewright/house-price-data/kaggle_london_house_price_data.csv")

print(house_prices_df)

"""**Observation**: 418,201 observations & 28 variables

# Conducting Exploratory Data Analysis (EDA)
"""

house_prices_df.head() # getting a view of the data

house_prices_df.info() # getting the structure of the data

"""**Observation**: Variables who have NaN values are:

bathrooms, bedrooms, floorAreaSqM, livingRooms, tenure, propertyType, currentEnergyRatng, rentEstimate_lowerPrice, rentEstimate_currentPrice, rentEstimate_upperPrice, rentEstimate_lowerPrice, saleEstimate_currentPrice, saleEstimate_upperPrice, saleEstimate_confidenceLevel, saleEstimate_ingestedAt, saleEstimate_valueChange.numericChange, saleEstimate_valueChange.percentageChange, saleEstimate_valueChange.saleDate, history_date, history_price, history_percentageChange, history_numericChange

**A very rough estimate is that up until almost 57% of the data has null values, based on the info from the last 2 variables.**
"""

house_prices_df.nunique() # getting the number of unique values and detecting potential duplicates

"""**Observations**: only 8325 unique records fo the history_date, this needs to be investigated.

### Descriptive Statistics
"""

house_prices_df.describe()

"""**Observation**: almost all variables present signs of having outliers, needs to be verified.

## Conducting distribution analysis
"""

#these will be used for filtering

ignored_variable_list = ["latitude", "longitude", "fullAddress", "postcode", "outcode", "country",
                         "saleEstimate_ingestedAt", "saleEstimate_valueChange.saleDate"]

date_variable_list = ["saleEstimate_ingestedAt", "saleEstimate_valueChange.saleDate", "history_date"]

categorical_variable_list = ["tenure", "propertyType", "currentEnergyRating", "saleEstimate_confidenceLevel"]

original_variables = house_prices_df.columns
original_variables = original_variables.tolist()

type(original_variables)
print(original_variables)

filtered_variables = original_variables

for item in ignored_variable_list:
    if item in filtered_variables:
        filtered_variables.remove(item)

for item in categorical_variable_list:
    if item in filtered_variables:
        filtered_variables.remove(item)

for item in date_variable_list:
    if item in filtered_variables:
        filtered_variables.remove(item)


print(filtered_variables) #filtered the non-essential variables

import matplotlib.pyplot as plt

for variable in filtered_variables:
    plt.hist(house_prices_df[variable], bins = 10)
    plt.title(variable)
    plt.xlabel("values")
    plt.ylabel("frequency")
    plt.show()

"""**Observation**: Outlier analysis cannot be done, unless we remove the NaN values first

# Next steps forward

**Recommendation**: Data cleaning will be in order for this dataset. Steps that will be taken into this direction:

- cleaning out the null values
- changing names for several valuables, to make the code clean
- dropping columns that are not required, the confidential ones at least
- converting some variables into date type (history_date, saledate) and integer (number of said rooms)
- if we are to pick linear regression, then we will need to drop the outliers
- rounding up the numerical values
- making sure that the data is balanced (will have to test this first)

all of this will be saved into a copy
"""